typography_spectrum: 0.18679
color:
  brandColors:
    - '#ececec'
    - '#011424'
    - '#4e6c82'
    - '#b26b23'
    - '#11c96f'
  brandStrength: 0.8125
  lightness: 0.1875
  saturation: 0.125
  rhythmicContrast: 1
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.39304660609923303
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Alexander Kucera
  email: a.kucera@babylondreams.de
  url: 'http://alexanderkucera.com'
name: Alex' Grid
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Alex' The Grid Testsite
content: []
purpose: []
