name: "Alex' Grid"
favicon: null
layout_spectrum: 0.39304660609923303
typography_spectrum: 0.18679
title: "Alex' The Grid Testsite"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ececec'
    - '#011424'
    - '#4e6c82'
    - '#b26b23'
    - '#11c96f'
  brandStrength: 0.8125
  lightness: 0.1875
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
