layout_spectrum: 0.14144731992449944
typography_spectrum: 0.650295737832047
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.5642462482711873
  lightness: 0.5406958633536787
  saturation: 0.3445479677806581
  rhythmicContrast: 0.9098027234186999
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Alexander Kucera
  email: a.kucera@babylondreams.de
  url: 'http://alexanderkucera.com'
name: Alex' Grid
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Alex' The Grid Testsite
content: []
purpose: []
